/**
 * file: photo types
 * author: Jubi
 * lastModify: Jubi 2021-6-4
 */
const SEARCH_PHOTOS_REQUEST = 'SEARCH_PHOTOS_REQUEST'
const GET_PHOTOS_SUCCEED = 'GET_PHOTOS_SUCCEED'
const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED'
const RANDOM_PHOTOS_REQUEST  = 'RANDOM_PHOTOS_REQUEST'



export {RANDOM_PHOTOS_REQUEST, SEARCH_PHOTOS_REQUEST, GET_PHOTOS_SUCCEED, GET_PHOTOS_FAILED}

